### ISSUE TITLE
Good reference to cache snooping?

### ISSUE THREAD

**Issue by bortzmeyer** [bortzmeyer/my-IETF-work#10]
There is a description of cache snooping in draft-ietf-dprive-problem-statement but no stable serious reference. Anyone has a suggestion for the bibliography?

**Comment by bortzmeyer** [comment]
A good one: http://www.msit2005.mut.ac.th/msit_media/1_2551/nete4630/materials/20080718130017Hc.pdf        DNS Cache Snooping
                    or
Snooping the Cache for Fun and Profit
       Version 1.1 / February 2004
              Luis Grangeia
        luis.grangeia@sidestep.pt

**Comment by edmonds** [comment]
FWIW, there is a brief description of a particular cache snooping countermeasure in the `unbound.conf` manpage (https://www.unbound.net/documentation/unbound.conf.html):

"The action allow_snoop gives nonrecursive access too. This give both recursive and non recursive access. The name allow_snoop refers to cache snooping, a technique to use nonrecursive queries to examine the cache contents (for malicious acts). However, nonrecursive queries can also be a valuable debugging tool (when you want to examine the cache contents). In that case use allow_snoop for your administration host.

**"By default only localhost is allowed, the rest is refused.** The default is refused, because that is protocol-friendly. The DNS protocol is not designed to handle dropped packets due to policy, and dropping may result in (possibly excessive) retried queries."
